services:
  - type: web
    name: hiring-pipeline-backend
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: "0"